### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by nazra-inari** [UBC-MDS/DSCI_522_Breast_cancer_predictors#1]
Hi Milos, 

I was thinking, for the proposal, we should have the following sections in the document:

1) Introduction (How and Why are we doing this)
2) The data source and a lil about the data and it's usage policy
3) The objective question that we will answer
4) The type of analysis that we will be conducting
5) A brief description of how this analysis will work. Big picture steps
6) How will the findings be reported

**Comment by milicmil** [comment]
Hi Arzan, Awesome. 

These are great subdivisions of the topics. I will work on expanding them. I should finish it today. Let me know what you think.
