### ISSUE TITLE
Reorder README

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Breast_cancer_predictors#28]
The Introduction/summary/overview (includes the objective/question) is probably the most important part of the file to engage readers, so this should come first.

Furthermore, there is duplication across some sections, typos in headers (FInal Report), and inconsistent capitalization in titles. The file should be carefully edited, as its the project's landing page and the first thing someone sees.

**Comment by milicmil** [comment]
I saw that too. Thank you for noticing it.
